### ISSUE TITLE
Rename this role on Galaxy

### ISSUE THREAD

**Issue by robled** [oasis-roles/openstack_provision#4]
The current URL/role name still has the underscore:

https://galaxy.ansible.com/oasis_roles/open_stack_provision

I spent some time in the Galaxy admin interface, but did not find a way to rename this.  I tried to deprecate, and then un-deprecate, to no effect.  Perhaps we need to try to delete the project in Galaxy and then re-import it.

**Comment by tehsmyers** [comment]
I don't remember the exact key, but I believe you can set the role's name in meta/main and galaxy should respect it.
